title: Stefano Perusi # your name (or website title) here
logo: "/images/foto_CV_black-white.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-LMDZKEHGZ0 # your Google Analytics tracking ID here
